services:
  fastapi:
    build: ../../Downloads/my_app_fastapi-main
    container_name: my-api-app
    volumes:
      - .:/app
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_URL: ${REDIS_URL}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_SERVER: ${MAIL_SERVER}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_FROM: ${MAIL_FROM}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME}
      DOMAIN: ${DOMAIN}
      ACCESS_TOKEN_EXPIRES_MINUTES: ${ACCESS_TOKEN_EXPIRES_MINUTES}
      ACCESS_TOKEN_EXPIRES_DEFAULT: ${ACCESS_TOKEN_EXPIRES_DEFAULT}
      REFRESH_TOKEN_EXPIRES_DAYS_DEFAULT: ${REFRESH_TOKEN_EXPIRES_DAYS_DEFAULT}
      MODEL_PATH: ${MODEL_PATH}
    ports:
      - "9000:9000"
    networks:
      - app-network

  celery:
    build: ../../Downloads/my_app_fastapi-main
    container_name: celery_worker
    command: celery -A app.celery_tasks.c_app worker -l info
    volumes:
      - .:/app
    environment:
      REDIS_URL: ${REDIS_URL}
    depends_on: []

    networks:
      - app-network

networks:
  app-network:
    driver: bridge


